@startuml
actor car_driver
actor customer
actor purchaser
actor student
actor client
actor atm_issues
participant ticket_machine
activate ticket_machine
car_driver -> ticket_machine: enter_coin_in_ticket_machine()
activate car_driver
participant coin
ticket_machine -> coin: validate()
activate coin
deactivate coin
ticket_machine -> car_driver: indicate()
activate car_driver
deactivate car_driver
car_driver -> ticket_machine: press_button_retrieve_parking_ticket()
participant parking_ticket
ticket_machine -> parking_ticket: print()
activate parking_ticket
deactivate parking_ticket
@enduml
